Stratio/egeo

src/st-tooltip/st-tooltip.component.html
src/st-tooltip/st-tooltip.component.spec.ts
src/st-tooltip/st-tooltip.component.ts

- Unit tests 
Add unit tests to st-tooltip component

[EGE-71]: Add unit tests to st-tooltip component

---

src/st-spinner/st-spinner.component.html
src/st-spinner/st-spinner.component.spec.ts
src/st-spinner/st-spinner.component.ts

- Unit tests 
Add unit tests to st-spinner.
Added input validation.
Modified the image src attribute to [src] directive.

[EGE-70]: Add test to st-spinner (#70)

---

config/spec-bundle.js
config/webpack.test.js

- New Feature
Be able to perform test by components
issue close  #119
Execute
`npm run test --component=[COMPONENT_NAME]`

[EGE-119] Add Test for component

---

README.md

- documentation
Add the waffle badge to the Readme
-

documentation(readme): add the waffle badge

---

.github/ISSUE_TEMPLATE.md

- Documentation
fix markdown bad-formed in the checkboxes of the issue template
Close #139 
-

fix(documentation): fix markdown bad-formed in the checkboxes of the issue template

---

README.md

- Documentation fix
change bad project name in file structure
- 

doc(readme): fix project name

---

src/st-tab-box/st-tab-box.component.scss

- Bugfix
St-tab-box componente  to be able to have the content to 100% of width
close #154

Bugfix styles St-tab-box

---

src/st-spinner/st-spinner.component.scss

- Bugfix and refactor
Remove external margins from spinner component

[EGE-182]: Remove external margins from spinner component

---

src/index.ts

- Bugfix
Add missing module export.

fix(st-table) Add missing module export

---

CHANGELOG.md
src/lib/barrels.ts
src/lib/public_api.ts
src/lib/st-switch/index.ts
src/lib/st-switch/st-switch.component.spec.ts
src/lib/st-switch/st-switch.component.ts
src/lib/st-switch/st-switch.html
src/lib/st-switch/st-switch.module.ts
src/lib/st-switch/st-switch.scss
src/lib/utils/egeo-form/egeo-form-utils.ts
src/lib/utils/egeo-form/index.ts
src/lib/utils/egeo-form/st-form-label/index.ts
src/lib/utils/egeo-form/st-form-label/st-form-label-status.enum.ts
src/lib/utils/egeo-form/st-form-label/st-form-label.component.html
src/lib/utils/egeo-form/st-form-label/st-form-label.component.scss
src/lib/utils/egeo-form/st-form-label/st-form-label.component.spec.ts
src/lib/utils/egeo-form/st-form-label/st-form-label.component.ts
src/lib/utils/egeo-form/st-form-label/st-form-label.module.ts

- New component
Close #166 
Create switch component

feat(st-switch): Create switch component

---

CHANGELOG.md
src/lib/st-table/index.ts
src/lib/st-table/shared/table-header.interface.ts
src/lib/st-table/st-table.component.html
src/lib/st-table/st-table.component.spec.ts
src/lib/st-table/st-table.component.ts

- Bugfix
Close #212 
Allow to introduce a model with id and label as header item

fix(st-table): Allow to add a model with id and label as header item

---

src/lib/st-search/st-search.component.scss
src/lib/st-search/st-search.component.spec.ts
src/lib/st-search/st-search.component.ts

- Improvements.
Add disabled state to st-search component. #201

feat(st-search): st-search component must have a disabled state

---

src/lib/st-switch/st-switch.component.spec.ts
src/lib/st-switch/st-switch.component.ts
src/lib/st-switch/st-switch.html
src/lib/st-switch/st-switch.scss
src/lib/st-tooltip/st-tooltip.component.scss
src/lib/utils/egeo-form/st-form-label/st-form-label.component.html
src/lib/utils/egeo-form/st-form-label/st-form-label.component.scss
src/lib/utils/egeo-form/st-form-label/st-form-label.component.spec.ts
src/lib/utils/egeo-form/st-form-label/st-form-label.component.ts

- Refactor of st-switch component
Add a description of your changes here.

refactor(st-switch): Improve template and behaviour when clicking on label

---

src/lib/decorators/require-decorators.ts
src/lib/public_api.ts
src/lib/st-modal/st-modal.component.ts
src/lib/st-spinner/st-spinner.component.ts
src/lib/st-switch/st-switch.component.ts
src/lib/st-table/st-table.component.ts
src/lib/st-two-list-selection/list-item/list-item.component.ts
src/lib/st-two-list-selection/list-selection/list-selection.component.ts
src/lib/st-two-list-selection/st-two-list-selection.component.ts
src/lib/st-two-list-selection/st-two-list-selection.view.component.ts
src/lib/utils/egeo-form/st-form-label/st-form-label.component.ts

- Refactor
- Refactor decorators.
- Rename egeo decorators.

refactor(decorators): refactor decorators

---

CHANGELOG.md
src/lib/st-header/st-header.component.ts

- Bugfix
Remove onpush strategy from st-Header this Pull request solved issues #148 and #248  

Bugfix submenu position

---

README.md

- Docs
Update readme 
close #251

docs(Readme): Update readme

---

src/lib/st-checkbox/st-checkbox.component.html
src/lib/st-checkbox/st-checkbox.component.scss
src/lib/st-checkbox/st-checkbox.component.ts

- Bugfix
Fixed wrong checkbox behavior. With the new behavior it returns the boolean state of the input checked

fix(St-checkbox): Bugfix st-checkbox

---

src/lib/barrels.ts
src/lib/st-form/st-form.component.html
src/lib/st-form/st-form.component.spec.ts
src/lib/st-form/st-form.component.ts
src/lib/st-form/st-form.module.ts

- Bugfix, New component, New service, Utils, etc.
Add a description of your changes here.

st-form initial file structure

---

CHANGELOG.md
src/lib/pipes/st-object-to-array/st-object-to-array.pipe.spec.ts
src/lib/pipes/st-object-to-array/st-object-to-array.pipe.ts

- Utils
Create a pipe to able to iterate over an object from a template. 

feature(st-object-to-array): Create pipe to iterate over an object from a template

---

CHANGELOG.md
src/lib/st-page-title/st-page-title.component.scss

- Bugfix
Fix left button position

fix(st-page-title): Fix left button position

---

CHANGELOG.md
src/lib/st-input/st-input.component.scss

- Bugfix
title margin on st-input

fix(st-input) #369 title margin on st-input

---

CHANGELOG.md
src/lib/st-vertical-tabs/st-vertical-tabs.component.scss

- Bugfix
click on the full option area

fix(vertical-tabs) #370 click on the full option area

---

CHANGELOG.md
src/lib/st-horizontal-tabs/st-horizontal-tabs.component.scss

- Bugfix
click on the full option area

fix(horizontal-tabs) #371 click on the full option area

---

src/lib/st-tree/demo/st-tree-demo.html
src/lib/st-tree/demo/st-tree-demo.module.ts
src/lib/st-tree/demo/st-tree-demo.ts
src/lib/st-tree/st-node-tree/st-node-tree.component.html
src/lib/st-tree/st-node-tree/st-node-tree.component.scss
src/lib/st-tree/st-tree.component.scss

- Bugfix
Fix overflow styles and improve demo

feat(st-tree): Fix overflow styles and improve demo

---

CHANGELOG.md
src/lib/barrels.ts
src/lib/directives/form/form-directives.module.ts
src/lib/directives/form/st-max-validator/st-max-validator.spec.ts
src/lib/directives/form/st-max-validator/st-max-validator.ts
src/lib/directives/form/st-min-validator/st-min-validator.spec.ts
src/lib/directives/form/st-min-validator/st-min-validator.ts
src/lib/public_api.ts
src/lib/st-input/st-input.component.html
src/lib/st-input/st-input.component.scss
src/lib/st-input/st-input.component.spec.ts
src/lib/st-input/st-input.component.ts
src/lib/st-input/st-input.error.model.ts

- New component
Close #EGE-387
Add number inputs and min/max validations

feat(st-input): Support number inputs with their validations

---

CHANGELOG.md
src/lib/st-toggle-buttons/st-toggle-buttons.interface.ts

feat(st-toggle-buttons): Add an optional id to the interface

---

CHANGELOG.md
src/lib/st-switch/st-switch.html

fix(st-switch): Change input id to <name>-input

---

src/demo-app/app/app.routing.ts
src/demo-app/app/layout/layout.menu.ts
src/egeo-demo/public_api.ts
src/egeo-demo/st-button-demo/st-button-demo.component.html
src/egeo-demo/st-button-demo/st-button-demo.component.scss
src/egeo-demo/st-button-demo/st-button-demo.component.ts
src/egeo-demo/st-button-demo/st-button-demo.module.ts

docs(button): add demo for button

---

src/egeo-demo/st-button-demo/st-button-demo.component.ts
src/lib/st-button/st-button.component.ts

fix(buttons): remove console.log

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/egeo-demo/st-switch-demo/st-switch-demo.html
src/lib/st-form/spec/resources/json-schema.ts
src/lib/st-form/spec/st-form.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.html
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.ts
src/lib/st-form/st-form.module.ts
src/lib/st-input/st-input.component.html
src/lib/st-switch/st-switch.component.spec.ts
src/lib/st-switch/st-switch.component.ts
src/lib/st-switch/st-switch.html
src/lib/utils/egeo-form/st-form-label/st-form-label.component.html

(st-form): Add switches to dynamic form

---

CHANGELOG.md
build-config.js
package.json
src/egeo-demo/package.json
src/lib/package.json

feat: Update theme to 0.14.0

---

src/egeo-demo/st-button-demo/st-button-demo.component.html
src/egeo-demo/st-button-demo/st-button-demo.component.scss

docs: added new buttons styles demo

---

src/demo-app/app/app.routing.ts
src/egeo-demo/public_api.ts
src/egeo-demo/st-textarea-demo/st-textarea-demo.html
src/egeo-demo/st-textarea-demo/st-textarea-demo.module.ts
src/egeo-demo/st-textarea-demo/st-textarea-demo.ts
src/lib/st-input/st-input.component.html
src/lib/st-input/st-input.component.scss
src/lib/st-input/st-input.component.ts
src/lib/st-textarea/st-textarea.component.html
src/lib/st-textarea/st-textarea.component.scss
src/lib/st-textarea/st-textarea.component.ts

refactor(st-input && st-textarea): Refactor st-input and textarea

---

CHANGELOG.md
src/demo-app/app/app.routing.ts
src/demo-app/app/layout/layout.component.html
src/demo-app/app/layout/layout.menu.ts
src/egeo-demo/public_api.ts
src/egeo-demo/st-checkbox-demo/st-checkbox-demo.component.html
src/egeo-demo/st-checkbox-demo/st-checkbox-demo.component.scss
src/egeo-demo/st-checkbox-demo/st-checkbox-demo.component.ts
src/egeo-demo/st-checkbox-demo/st-checkbox-demo.module.ts
src/lib/st-checkbox/st-checkbox.component.ts

refactor(st-checkbox): update style and added demo

---

CHANGELOG.md
src/demo-app/app/app.component.scss
src/demo-app/app/app.routing.ts
src/demo-app/app/layout/layout.menu.ts
src/egeo-demo/public_api.ts
src/egeo-demo/st-table-demo/st-table-demo.component.html
src/egeo-demo/st-table-demo/st-table-demo.component.scss
src/egeo-demo/st-table-demo/st-table-demo.component.ts
src/egeo-demo/st-table-demo/st-table-demo.module.ts
src/lib/st-table/shared/st-table-cell/st-table-cell.component.scss
src/lib/st-table/shared/st-table-row/st-table-row.component.spec.ts
src/lib/st-table/shared/st-table-row/st-table-row.component.ts
src/lib/st-table/st-table.component.html
src/lib/st-table/st-table.component.scss
src/lib/st-table/st-table.component.spec.ts
src/lib/st-table/st-table.component.ts
src/theme/components/_table.scss

refactor(st-table): Add new style and demo

---

CHANGELOG.md
src/egeo-demo/st-table-demo/st-table-demo.component.html
src/egeo-demo/st-table-demo/st-table-demo.component.scss
src/egeo-demo/st-table-demo/st-table-demo.component.ts
src/egeo-demo/st-table-demo/st-table-demo.module.ts
src/lib/st-table/README.md
src/lib/st-table/shared/st-table-row/st-table-row.component.ts
src/lib/st-table/st-table.component.html
src/lib/st-table/st-table.component.spec.ts
src/lib/st-table/st-table.component.ts
src/lib/st-table/st-table.module.ts
src/theme/components/_table.scss

feat(st-table): Add functionality to select rows optionally 

---

CHANGELOG.md
src/egeo-demo/st-checkbox-demo/st-checkbox-demo.component.html
src/lib/st-checkbox/README.md
src/lib/st-checkbox/st-checkbox.component.html
src/lib/st-checkbox/st-checkbox.component.ts
src/theme/components/_checkbox.scss

fix(st-checkbox): Fix disabled style

---

CHANGELOG.md
src/egeo-demo/st-switch-demo/st-switch-demo.html
src/egeo-demo/st-switch-demo/st-switch-demo.scss
src/lib/st-form/spec/st-form.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-switch/st-switch.component.spec.ts
src/lib/st-switch/st-switch.component.ts
src/lib/st-switch/st-switch.html
src/lib/st-switch/st-switch.module.ts
src/lib/st-switch/st-switch.scss

BREAKING CHANGE: st-switch: Remove labelPosition input
cct-99

style(st-switch): Apply new style

---

src/egeo-demo/egeo-demo.routes.ts
src/egeo-demo/public_api.ts
src/egeo-demo/st-widget-demo/st-widget-demo.component.html
src/egeo-demo/st-widget-demo/st-widget-demo.component.scss
src/egeo-demo/st-widget-demo/st-widget-demo.component.ts
src/egeo-demo/st-widget-demo/st-widget-demo.module.ts
src/lib/barrels.ts
src/lib/public_api.ts
src/lib/st-widget/README.md
src/lib/st-widget/st-widget.component.html
src/lib/st-widget/st-widget.component.scss
src/lib/st-widget/st-widget.component.spec.ts
src/lib/st-widget/st-widget.component.ts
src/lib/st-widget/st-widget.module.ts
src/theme/components/_index.scss
src/theme/components/_widget.scss

feat(St-Widget): Create Widget component

---

CHANGELOG.md
src/egeo-demo/st-textarea-demo/st-textarea-demo.html
src/egeo-demo/st-textarea-demo/st-textarea-demo.scss
src/egeo-demo/st-textarea-demo/st-textarea-demo.ts
src/lib/st-textarea/README.md
src/lib/st-textarea/st-textarea.component.html
src/lib/st-textarea/st-textarea.component.spec.ts
src/lib/st-textarea/st-textarea.component.ts
src/lib/st-textarea/st-textarea.module.ts
src/theme/components/_textarea.scss

refactor(st-textarea): Add st-label directive and minor fixes to style

---

CHANGELOG.md
src/theme/grid/grid.scss

[CCT-167] bug(Grid): Grid wrong behavior

---

src/egeo-demo/st-select-demo/select-demo.html
src/lib/st-label/st-label.component.ts
src/lib/st-select/README.md
src/lib/st-select/st-select.component.html
src/lib/st-select/st-select.component.spec.ts
src/lib/st-select/st-select.component.ts
src/lib/st-select/st-select.module.ts
src/theme/components/_select.scss

refactor(st-select): added label and other styles fixes

---

CHANGELOG.md
src/egeo-demo/st-input-demo/st-input-demo.component.scss
src/egeo-demo/st-input-demo/st-input-demo.html
src/egeo-demo/st-input-demo/st-input-demo.ts
src/lib/st-form/spec/st-form.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-input/st-input.component.html
src/lib/st-input/st-input.component.spec.ts
src/lib/st-input/st-input.component.ts
src/lib/st-input/st-input.module.ts
src/lib/st-select/st-select.component.html
src/lib/st-select/st-select.component.spec.ts
src/lib/st-select/st-select.component.ts
src/lib/st-switch/st-switch.component.spec.ts
src/lib/st-switch/st-switch.component.ts
src/lib/st-switch/st-switch.html
src/lib/st-textarea/st-textarea.component.html
src/lib/st-textarea/st-textarea.component.scss
src/theme/components/_input.scss
src/theme/components/_select.scss
src/theme/components/_switch.scss
src/theme/components/_textarea.scss
src/theme/utils/_forms.scss

refactor(st-input): Apply new styles and refactor them to can be applied to a native input

---

src/egeo-demo/st-input-demo/st-input-demo.component.scss
src/egeo-demo/st-input-demo/st-input-demo.html
src/egeo-demo/st-input-demo/st-input-demo.ts
src/egeo-demo/st-select-demo/select-demo.scss
src/lib/st-label/st-label.component.scss
src/lib/st-textarea/st-textarea.component.scss
src/theme/components/_select.scss
src/theme/components/_switch.scss
src/theme/utils/_forms.scss

refactor(st-input, st-select, st-switch): Add minor changes requested by UX

---

package.json
src/demo-app/polyfills.ts
src/egeo-demo/st-table-demo/st-table-demo.component.html
src/egeo-demo/st-table-demo/st-table-demo.component.scss
src/lib/st-table/README.md
src/lib/st-table/shared/st-table-cell/st-table-cell.component.scss
src/lib/st-table/shared/st-table-row/README.md
src/lib/st-table/shared/st-table-row/st-table-row.component.html
src/lib/st-table/shared/st-table-row/st-table-row.component.spec.ts
src/lib/st-table/shared/st-table-row/st-table-row.component.ts
src/lib/st-table/st-table.component.html
src/lib/st-table/st-table.component.scss
src/lib/st-table/st-table.component.spec.ts
src/lib/st-table/st-table.component.ts
src/theme/components/_table.scss

 [CCT-228]feat(st-table): Add functionality to fix header and minor UX changes

---

CHANGELOG.md
src/egeo-demo/st-widget-demo/st-widget-demo.component.html
src/egeo-demo/st-widget-demo/st-widget-demo.component.scss
src/lib/st-widget/st-widget.component.html
src/lib/st-widget/st-widget.component.scss
src/lib/st-widget/st-widget.component.spec.ts
src/lib/st-widget/st-widget.component.ts
src/lib/st-widget/st-widget.module.ts

[CCT-482]feat(st-widget)implement loading state

---

CHANGELOG.md
package.json
src/egeo-demo/st-modal-demo/st-modal-demo.component.html
src/egeo-demo/st-modal-demo/st-modal-demo.component.ts
src/egeo-demo/st-modal-demo/st-modal-demo.module.ts
src/egeo-demo/st-modal-demo/st-modal-test-buttons-demo.component.ts
src/lib/public_api.ts
src/lib/st-modal/st-modal.component.html
src/lib/st-modal/st-modal.model.ts
src/lib/st-modal/st-modal.service.spec.ts
src/lib/st-modal/st-modal.service.ts

[CCT-413 & CCT-466]fix(modal): Buttons position and space

---

src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.ts
src/lib/st-foreground-notifications/st-foreground-notifications.scss
src/lib/st-foreground-notifications/st-foreground-notifications.spec.ts
src/lib/st-foreground-notifications/st-foreground-notifications.ts

[CCT-432]refactor(foreground-notifications)

---

CHANGELOG.md
src/lib/st-fullscreen-layout/st-fullscreen-layout.scss
src/lib/st-tag-input/st-tag-input.component.ts

fix(st-fullscreen-layout)[CCT-607]: Fix scroll

---

src/theme/components/_form-base.scss

[NA]fix(theme): fixed form styles

---

src/theme/components/_form-base.scss

[NA]fix(theme): fixed form styles (#513)

---

src/lib/st-textarea/st-textarea.component.scss

fix(st-textarea)[CCT-424]: Textarea resize does not work correctly

---

CHANGELOG.md
src/egeo-demo/st-search-demo/st-search-demo.html
src/egeo-demo/st-search-demo/st-search-demo.scss
src/egeo-demo/st-search-demo/st-search-demo.ts
src/egeo-demo/st-select-demo/select-demo.html
src/egeo-demo/st-select-demo/select-demo.scss
src/lib/st-header/menu-option/menu-option.ts
src/lib/st-modal/st-modal.component.ts
src/lib/st-search/README.md
src/lib/st-search/st-search.component.html
src/lib/st-search/st-search.component.scss
src/lib/st-search/st-search.component.spec.ts
src/lib/st-search/st-search.component.ts
src/lib/st-search/st-search.module.ts
src/lib/utils/event-window-manager.ts
src/theme/components/_dropdown-menu.scss
src/theme/components/_search.scss
src/theme/components/_select.scss
src/theme/utils/_forms.scss

feat(st-search)[NA]: Add a select to generate filtered searches

---

CHANGELOG.md
src/egeo-demo/st-widget-demo/st-widget-demo.component.html
src/lib/st-label/st-label.component.spec.ts
src/lib/st-widget/README.md
src/lib/st-widget/st-widget.component.html
src/lib/st-widget/st-widget.component.spec.ts
src/lib/st-widget/st-widget.component.ts
src/lib/tests/utils.ts
test/karma.conf.js

feat(st-widget)[NA]: Add settings button and draggable action as optional

---

CHANGELOG.md
src/demo-app/app/shared/header/header.component.scss
src/lib/st-alerts/st-alerts.component.html
src/lib/st-fullscreen-layout/st-fullscreen-layout.scss
src/lib/st-modal/st-modal.component.scss
src/lib/st-tag-input/st-tag-input.component.spec.ts
src/theme/components/_alerts.scss
src/theme/components/_fullscreen-layout.scss
src/theme/components/_header.scss
src/theme/components/_modal.scss
src/theme/constants/_index.scss
src/theme/constants/_settings.scss

fix(st-alert))[NA]: Predefine z-index variables for fixed components

---

src/egeo-demo/st-input-demo/st-input-demo.html
src/egeo-demo/st-input-demo/st-input-demo.ts

doc(st-input)[NA]: Improve input example with enabled and disabled inputs

---

CHANGELOG.md
src/egeo-demo/st-input-demo/st-input-demo.html
src/egeo-demo/st-input-demo/st-input-demo.ts
src/theme/utils/_forms.scss

Revert "fix(st-input)[UX-29]: Add a gray color to input text when it is disabled and it has value"

---

CHANGELOG.md
src/lib/st-pagination/st-pagination.component.ts

fix(st-pagination)[UX-35]: Fix error when a change is listened from outside

---

src/lib/st-pagination/st-pagination.component.spec.ts
src/lib/st-pagination/st-pagination.component.ts

fix(st-pagination): Do not perform any action when changes are listened when pagination is being created

---

CHANGELOG.md
src/theme/components/_header.scss

fix(st-header)[UX-41]: Fix z-index

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/egeo-demo/st-form-demo/st-form-demo.html
src/egeo-demo/st-form-demo/st-form-demo.ts
src/egeo-demo/st-form-list-demo/st-form-list-demo.ts
src/lib/st-form-list/spec/st-form-list.component.spec.ts
src/lib/st-form/README.md
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.ts
src/lib/st-form/st-form.component.ts

feat(st-form)[UX-72]: Allow to render read only fields

---

CHANGELOG.md
src/lib/st-form-list/st-form-list.component.ts

fix: fix st-form-list formArray refresh

---

CHANGELOG.md
src/lib/st-modal/st-modal.component.html
src/theme/components/_tooltip.scss

style(st-tooltip)[UX-39]: Apply new style

---

CHANGELOG.md
src/lib/st-pagination/README.md
src/lib/st-pagination/st-pagination.component.html
src/lib/st-pagination/st-pagination.component.scss
src/lib/st-pagination/st-pagination.component.ts
src/theme/components/_pagination.scss

style(st-pagination)[UX-62]: Apply new style

---

CHANGELOG.md
src/lib/st-form-list/st-form-list.component.ts

Cherry pick 8.5.1

---

CHANGELOG.md
src/lib/st-sidebar/st-sidebar.component.html
src/lib/st-sidebar/st-sidebar.component.ts

fix(st-sidebar): Fix bug when there are an active item and another one with an added class

---

CHANGELOG.md
src/lib/st-sidebar/st-sidebar.component.html
src/lib/st-sidebar/st-sidebar.component.ts

cherry-pick fix(st-sidebar): Fix bug when there are an active item and another one with an added class

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/lib/st-form/spec/st-form.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.html
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.ts
src/lib/st-form/st-form-field/st-form-field.module.ts
src/lib/st-form/st-form.component.html
src/lib/st-form/st-form.component.ts
src/lib/st-form/st-form.module.ts

 feat(st-form)[UX-70]: Allow to add dependant fields

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/lib/st-form/README.md
src/lib/st-form/shared/ui-component.interface.ts
src/lib/st-form/spec/st-form.component.spec.ts
src/lib/st-form/st-form.component.html
src/lib/st-form/st-form.component.ts
src/theme/components/_form.scss

feat(st-form)[UX-78]:Allow to show and hide entire sections clicking a link button and using the ui attribute 'component'

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/egeo-demo/st-form-demo/st-form-demo.html
src/lib/st-form/shared/ui-component.interface.ts
src/lib/st-form/spec/st-form.component.spec.ts
src/lib/st-form/st-form.component.html
src/lib/st-form/st-form.component.ts
src/theme/components/_form.scss

 feat(st-form)[UX-79]: Display sections as accordion visualization in dynamic form

---

CHANGELOG.md
pom.xml

[RELEASE] 8.7.0

---

package.json
pom.xml

Prepare for next version

---

CHANGELOG.md

Noting 8.7.0 release date

---

CHANGELOG.md
src/lib/st-label/st-label.component.ts
src/theme/components/_form-base.scss

fix(st-tooltip)[UX-90]: Fix displaying of tooltip in AOT

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/egeo-demo/st-form-demo/st-form-demo.html
src/lib/st-form/spec/resources/json-schema.ts
src/lib/st-form/spec/st-form.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-form/st-form.component.html
src/lib/st-form/st-form.component.ts
src/theme/components/_form-base.scss
src/theme/components/_form.scss

feat(st-form)[UX-72]: Allow to display related fields in the same row

---

CHANGELOG.md

fix(changelog)[NA]: Fix changelog

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/lib/st-form/spec/st-form.component.spec.ts
src/lib/st-form/st-form.component.html
src/lib/st-form/st-form.component.ts

feat(st-form)[UX-99]: Allow to display and hide fields according to the value of another field

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.html
src/egeo-demo/st-textarea-demo/st-textarea-demo.html
src/lib/st-foreground-notifications/st-foreground-notifications.scss
src/lib/st-form/README.md
src/lib/st-form/st-form.component.html
src/lib/st-form/st-form.component.ts
src/theme/components/_button.scss
src/theme/components/_checkbox.scss
src/theme/components/_foreground-notifications.scss
src/theme/components/_form-base.scss
src/theme/components/_form-list.scss
src/theme/components/_index.scss
src/theme/components/_radio.scss
src/theme/components/_search.scss
src/theme/components/_select.scss
src/theme/components/_switch.scss
src/theme/components/_tag-input.scss
src/theme/utils/_forms.scss

style(several components)[UX-75]: Apply visual changes for contrast improvements

---

src/lib/st-checkbox/st-checkbox.component.html
src/lib/st-form/st-form-field/st-form-field.component.html

[NA]fix(st-checkbox): Fix tooltips to checkboxes

---

CHANGELOG.md
src/egeo-demo/st-draggable-card-demo/st-draggable-card-demo.component.html
src/egeo-demo/st-draggable-card-demo/st-draggable-card-demo.component.ts
src/lib/st-draggable-card/st-draggable-card.component.spec.ts
src/lib/st-draggable-card/st-draggable-card.component.ts

[NA] fix(st-draggable-card): Fix st-draggable-card delay and performance

---

CHANGELOG.md
pom.xml

Prepare for 8.9.0 release

---

CHANGELOG.md
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.ts

feat(st-form)[NA]: Remove e.g from placeholders

---

src/lib/st-tree/st-tree.component.html
src/lib/st-tree/st-tree.component.scss
src/theme/components/_tree.scss

fix tree css for overflow text

---

CHANGELOG.md
src/lib/st-form/st-form.component.ts

fix(st-form)[NA]: Fix validations of nested properties

---

CHANGELOG.md
src/egeo-demo/st-tree-demo/st-tree-demo.ts
src/lib/st-tree/README.md
src/lib/st-tree/st-tree.component.html
src/lib/st-tree/st-tree.component.spec.ts
src/lib/st-tree/st-tree.component.ts
src/lib/st-tree/st-tree.model.ts
src/theme/components/_form.scss

refactor(st-tree)[NA]: Increment test coverage

---

CHANGELOG.md
src/egeo-demo/st-form-demo/json-schema.ts
src/lib/st-form/st-form.component.ts

[NA]fix(st-from)setting form as Pristine

---

CHANGELOG.md
src/lib/st-sidebar/st-sidebar.component.spec.ts
src/lib/st-sidebar/st-sidebar.component.ts

fix(st-sidebar)[NA]: Remove internal modification of the active item

---

CHANGELOG.md
pom.xml
src/lib/st-sidebar/st-sidebar.component.spec.ts
src/lib/st-sidebar/st-sidebar.component.ts

 fix(st-sidebar)[NA]: Fix stateless sidebar

---

CHANGELOG.md

Fix changelog to release 10.0.1

---

CHANGELOG.md
src/egeo-demo/st-form-list-demo/st-form-list-demo.ts
src/lib/st-form-list/st-form-list.scss

[NA]fix(st-form-list): Select dropdown is not displayed

---

CHANGELOG.md
src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.html
src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.ts
src/lib/st-foreground-notifications/st-foreground-notifications.spec.ts
src/lib/st-foreground-notifications/st-foreground-notifications.ts

[NA] feat(foreground notification): Add autoclose property to close it automatically

---

src/theme/components/_header.scss

[SAAS-304]fix(header): set cursor pointer

---

CHANGELOG.md
src/theme/components/_button.scss
src/theme/components/_form-base.scss

[NA] feat(egeo-theme): Changes in labels and buttons styles

---

CHANGELOG.md
src/theme/components/_form.scss

[SAAS-357] enhancement(dynamic form): Improve margins between fields and sections

---

src/demo-app/app/modules/theme/icons-demo/icons-demo.ts
src/lib/pipes/pipes.module.ts
src/lib/pipes/search-filter.pipe.ts
src/lib/pipes/search-filter/search-filter.pipe.spec.ts
src/lib/pipes/search-filter/search-filter.pipe.ts
src/lib/public_api.ts

[NA] fix(demo): Fix search in icon list

---

CHANGELOG.md
src/theme/vendors/fonts/_stratio_fonticon.scss

[NA] cherry-pick: Fix icon font styles

---

CHANGELOG.md
src/egeo-demo/barrels.ts
src/egeo-demo/egeo-demo.routes.ts
src/egeo-demo/public_api.ts
src/egeo-demo/st-bubble-demo/st-bubble-demo.component.html
src/egeo-demo/st-bubble-demo/st-bubble-demo.component.scss
src/egeo-demo/st-bubble-demo/st-bubble-demo.component.ts
src/egeo-demo/st-bubble-demo/st-bubble-demo.module.ts
src/lib/barrels.ts
src/lib/public_api.ts
src/lib/st-bubble/README.md
src/lib/st-bubble/st-bubble.component.html
src/lib/st-bubble/st-bubble.component.scss
src/lib/st-bubble/st-bubble.component.spec.ts
src/lib/st-bubble/st-bubble.component.ts
src/lib/st-bubble/st-bubble.module.ts
src/lib/st-launcher/st-launcher.component.spec.ts
src/lib/st-launcher/st-launcher.component.ts
src/theme/components/_bubble.scss
src/theme/components/_index.scss

[NA] feat(st-bubble): Create component

---

CHANGELOG.md
src/egeo-demo/st-button-demo/st-button-demo.component.html
src/theme/components/_button.scss
src/theme/constants/_colors.scss

[SAAS-426] feat(st-button):Add small button style

---

CHANGELOG.md
src/egeo-demo/st-input-demo/st-input-demo.ts
src/theme/components/_checkbox.scss
src/theme/components/_form-base.scss
src/theme/components/_radio.scss
src/theme/components/_select.scss
src/theme/components/_tag-input.scss
src/theme/constants/_colors.scss

…TagInput, StCheckbox, StRadio): New disabled style

[SAAS-431,432,433,434,435,436] feat(StInput, StTextArea, StSelect, StTagInput, StCheckbox, StRadio): New disabled style

---

CHANGELOG.md
src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.html
src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.ts
src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
src/lib/st-two-list-selection/list-scroll/list-scroll.component.spec.ts
src/lib/st-two-list-selection/list-scroll/list-scroll.component.ts
src/lib/st-two-list-selection/list-selection/list-selection.component.html
src/lib/st-two-list-selection/list-selection/list-selection.component.ts
src/lib/st-two-list-selection/st-two-list-selection.component.ts
src/lib/st-two-list-selection/st-two-list-selection.model.ts
src/lib/st-two-list-selection/st-two-list-selection.spec.ts
src/lib/st-two-list-selection/st-two-list-selection.ts
src/lib/st-two-list-selection/st-two-list-selection.view.component.html
src/lib/st-two-list-selection/st-two-list-selection.view.component.ts

Bloqueada - Pendiente definición UX

[SECTY-436] feat( st-two-list): includes checkbox all button

---

CHANGELOG.md
src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.html
src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.ts
src/lib/public_api.ts
src/lib/st-breadcrumbs/README.md
src/lib/st-breadcrumbs/st-breadcrumbs-item/st-breadcrumbs-item.component.html
src/lib/st-breadcrumbs/st-breadcrumbs.component.html
src/lib/st-breadcrumbs/st-breadcrumbs.component.spec.ts
src/lib/st-breadcrumbs/st-breadcrumbs.component.ts
src/lib/st-breadcrumbs/st-breadcrumbs.interface.ts

[SAAS-437] feat(StBreadCrumb): Update breadcrumb to allow icons

---

src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.ts
src/lib/st-breadcrumbs/README.md
src/lib/st-breadcrumbs/st-breadcrumbs-item/st-breadcrumbs-item.component.spec.ts
src/lib/st-breadcrumbs/st-breadcrumbs.component.spec.ts
src/lib/st-breadcrumbs/st-breadcrumbs.component.ts
src/lib/st-breadcrumbs/st-breadcrumbs.interface.ts

[SAAS-437] feat(StBreadCrumb): Add ID parameter to the model

---

CHANGELOG.md
src/egeo-demo/st-modal-demo/st-modal-demo.component.ts
src/lib/st-modal/st-modal.component.spec.ts
src/lib/st-modal/st-modal.component.ts
src/lib/st-modal/st-modal.model.ts
src/lib/st-modal/st-modal.service.spec.ts
src/lib/st-modal/st-modal.service.ts

[SAAS-439] feat(StModal):Set default max and min width

---

CHANGELOG.md
pom.xml

[NA] chore(release): Prepare changelog and pom for release 12.0.0

---

CHANGELOG.md
src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.html
src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.scss
src/lib/st-sidebar/st-sidebar.component.html
src/lib/st-sidebar/st-sidebar.component.spec.ts

[SAAS-448] feat(st-sidebar): Allow to add any content from outside to header and footer

---

CHANGELOG.md
src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.html
src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
src/lib/public_api.ts
src/lib/st-breadcrumbs/README.md
src/lib/st-breadcrumbs/st-breadcrumbs.component.ts
src/lib/st-dropdown-menu/README.md
src/lib/st-dropdown-menu/st-dropdown-menu.component.html
src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
src/lib/st-sidebar/st-sidebar.component.spec.ts
src/theme/components/_dropdown-menu.scss

[NA] feat(st-dropdown-menu): Allow to add a visual mode in order to display it as option or menu list

---

CHANGELOG.md
src/theme/components/_dropdown-menu.scss

[NA] feat(st-dropdown-menu): Put pointer cursor to items

---

CHANGELOG.md
src/theme/components/_bubble.scss

[SAAS-495] fix(st-bubble): Fix visible style

---

CHANGELOG.md
src/theme/components/_dropdown-menu.scss

[NA] fix(st-dropdown-menu): Fix wrong visualization on small screens

---

CHANGELOG.md
src/theme/components/_dropdown-menu.scss

[NA] style(st-dropdown-menu): Improve item design

---

CHANGELOG.md
src/theme/components/_button.scss
src/theme/components/_input.scss
src/theme/components/_spinner.scss
src/theme/utils/_fonts.scss
src/theme/utils/_forms.scss

[NA] style(st-button, st-input, st-spinner): Apply minor style changes

---

CHANGELOG.md
src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
src/lib/st-two-list-selection/list-selection/list-selection.component.scss

[NA] feat(st-two-list): adds new styles

---

CHANGELOG.md
src/demo-app/app/modules/general/about/about.scss
src/demo-app/styles.scss
src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.html
src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.ts
src/lib/st-tag-input/README.md
src/lib/st-tag-input/st-tag-input.component.html
src/lib/st-tag-input/st-tag-input.component.spec.ts
src/lib/st-tag-input/st-tag-input.component.ts

[NA] feat(st-tag-input): Allow user to generate arrays of integers and numbers

---

CHANGELOG.md
pom.xml
src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.component.scss
src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.html
src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.ts

[NA] enhanement(st-dropdown-menu): Fix demo and next release version

---

CHANGELOG.md
src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
src/lib/st-two-list-selection/list-selection/list-selection.component.html
src/lib/st-two-list-selection/list-selection/list-selection.component.scss

[NA] fix(st-two-list): bad behavior with virtual scroll and checkbox all

---

angular.json
src/demo-app/app/modules/general/changelog/changelog.scss
src/demo-app/app/modules/general/getting-started/getting-started.scss
src/demo-app/app/modules/theme/grid/grid.scss
src/demo-app/app/shared/menu/menu.scss

[NA] fix(web): Fix web generator task and add some minor style changes

---

src/lib/st-form/st-form.component.html

[SAAS-604] feat(st-form): Add ID parameter to the component

---

CHANGELOG.md
src/lib/st-select/st-select.html
src/lib/st-select/st-select.spec.ts
src/lib/st-select/st-select.ts

[NA] fix(st-select): When select is in a form, user has to click two times in an option to select it

---

CHANGELOG.md
src/lib/st-tag-input/st-tag-input.component.html

[NA] fix(st-tag-input): Remove array value as string from view

---

CHANGELOG.md
src/lib/st-tag-input/st-tag-input.component.html

Cherry pick: [NA] fix(st-tag-input): Remove array value as string from view

---

CHANGELOG.md
src/lib/st-form/st-form-field/st-form-field.component.html
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.ts
src/lib/st-select/st-select.ts

Cherry-pick: [NA fix (st-select): When select is in a form, user stil l has to click two times to select an option

---

CHANGELOG.md
src/lib/st-form/st-form-field/st-form-field.component.html
src/lib/st-form/st-form-field/st-form-field.component.spec.ts
src/lib/st-form/st-form-field/st-form-field.component.ts
src/lib/st-select/st-select.html
src/lib/st-select/st-select.ts

[NA fix (st-select): When select is in a form, user still has to click two times to select an option

---

CHANGELOG.md
src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.html
src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.scss
src/lib/st-horizontal-tabs/st-horizontal-tabs.component.html
src/lib/st-horizontal-tabs/st-horizontal-tabs.component.scss
src/lib/st-horizontal-tabs/st-horizontal-tabs.component.spec.ts
src/lib/st-horizontal-tabs/st-horizontal-tabs.component.ts
src/theme/components/_horizontal-tabs.scss

[NA] feat(st-horizontal-tabs): Apply new design according to UX specifications

---

CHANGELOG.md
src/egeo-demo/st-modal-demo/st-modal-demo.component.ts
src/lib/st-modal/st-modal.component.html
src/lib/st-modal/st-modal.component.spec.ts
src/lib/st-modal/st-modal.component.ts
src/lib/st-modal/st-modal.model.ts
src/theme/components/_modal.scss

[NA] feat(st-modal): Allow to add a cross button to close modal

---

CHANGELOG.md
src/lib/directives/st-click-outside/st-click-outside.component.spec.ts
src/lib/directives/st-click-outside/st-click-outside.directive.ts
src/lib/public_api.ts
src/lib/st-select/st-select.html
src/lib/st-select/st-select.module.ts
src/lib/st-select/st-select.spec.ts
src/lib/st-select/st-select.ts

[NA fix (st-select): Close select when user clicks outside

---

CHANGELOG.md
src/lib/directives/st-click-outside/st-click-outside.component.spec.ts
src/lib/directives/st-click-outside/st-click-outside.directive.ts
src/lib/public_api.ts
src/lib/st-select/st-select.html
src/lib/st-select/st-select.module.ts
src/lib/st-select/st-select.spec.ts
src/lib/st-select/st-select.ts

Cherry-pick: [NA] fix (st-select): Close select when user clicks outside

---

CHANGELOG.md
src/lib/st-file-button/README.md
src/lib/st-file-button/st-file-button.component.html
src/lib/st-file-button/st-file-button.component.ts

[NA] fix(st-file-button): add id to input

---

CHANGELOG.md
src/lib/st-textarea/st-textarea.component.scss

[EGE-436] (st-text-area): fix error style

---

CHANGELOG.md
src/lib/st-select/st-select.html

[EGE-446] fix(st-select): Disable native autocomplete

---

CHANGELOG.md
src/egeo-demo/st-fullscreen-layout-demo/st-fullscreen-layout-demo.html
src/egeo-demo/st-fullscreen-layout-demo/st-fullscreen-layout-demo.scss
src/lib/st-fullscreen-layout/README.md
src/lib/st-fullscreen-layout/st-fullscreen-layout.html
src/lib/st-fullscreen-layout/st-fullscreen-layout.spec.ts
src/lib/st-fullscreen-layout/st-fullscreen-layout.ts
src/theme/components/_fullscreen-layout.scss

[EGE-448] fix(st-fullscreen): Allow to customize title

---

src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.html
src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.ts
src/lib/st-foreground-notifications/st-foreground-notifications.spec.ts
src/lib/st-foreground-notifications/st-foreground-notifications.ts

[NA] fix(st-foreground-notifications): doesnt change visible var value inside component

---

angular.json
package.json
src/lib/st-docs/st-prism/st-prism.component.ts
test/karma.conf.js

[NA] fix(prismjs): Fix dependency

---

CHANGELOG.md
src/egeo-demo/st-table-demo/st-table-demo.component.html
src/egeo-demo/st-table-demo/st-table-demo.component.scss
src/egeo-demo/st-table-demo/st-table-demo.component.ts
src/lib/st-table/README.md
src/lib/st-table/shared/st-table-cell/st-table-cell.component.scss
src/lib/st-table/st-table.component.html
src/lib/st-table/st-table.component.scss
src/lib/st-table/st-table.component.spec.ts
src/lib/st-table/st-table.component.ts
src/theme/components/_table.scss

[EGE-443] feat(table): Allow display tables with white and default themes

---

CHANGELOG.md
src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.ts
src/lib/public_api.ts
src/lib/st-horizontal-tabs/README.md
src/lib/st-horizontal-tabs/st-horizontal-tabs.component.html
src/lib/st-horizontal-tabs/st-horizontal-tabs.component.spec.ts
src/lib/st-horizontal-tabs/st-horizontal-tabs.component.ts
src/lib/st-horizontal-tabs/st-horizontal-tabs.model.ts
src/theme/components/_horizontal-tabs.scss

[EGE-476] feat(horizontal tabs): Allow to add classes to tabs according to its status

---

CHANGELOG.md
src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.ts
src/theme/components/_sidebar.scss

[EOS-1679] fix(st-sidebar): fix minor style bug

---

CHANGELOG.md
src/egeo-demo/st-table-demo/st-table-demo.component.html
src/egeo-demo/st-table-demo/st-table-demo.component.scss
src/lib/st-table/README.md
src/lib/st-table/st-table.component.html
src/lib/st-table/st-table.component.spec.ts
src/lib/st-table/st-table.component.ts

[EGEO-443] feat(table): Revert changes in tables with fixed header

---

CHANGELOG.md
src/lib/st-table/shared/st-table-row/st-table-row.component.scss
src/theme/components/_table.scss

[NA] fix(table):  Remove transition for all attributes in order to prevent a wrong behaviour

---

CHANGELOG.md
src/theme/components/_modal.scss

[EOS-1698] fix(st-modal): fix minor style bug

---

CHANGELOG.md
src/lib/st-two-list-selection/list-selection/list-selection.component.html
src/lib/st-two-list-selection/list-selection/list-selection.component.spec.ts
src/lib/st-two-list-selection/list-selection/list-selection.component.ts
src/lib/st-two-list-selection/st-two-list-selection.spec.ts

[EGE-477] fix(two-list): Searcher disappears when user is typing and introduces a text without results

---

CHANGELOG.md
src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.html
src/lib/st-breadcrumbs/st-breadcrumbs.component.scss
src/theme/components/_modal.scss

Cherry pick  [EOS-1698] fix(st-modal, st-breadcrumbs): fix minor style bug 

---

pom.xml

Update pom release version to 16.1.0

---

src/theme/components/_dropdown-menu.scss
src/theme/components/_form-base.scss
src/theme/components/_fullscreen-layout.scss
src/theme/components/_header.scss
src/theme/components/_search.scss
src/theme/components/_table.scss
src/theme/components/_widget.scss

[NA] fix(st-widget, form-base, fullscreen,header, search,table): Add font family

---

CHANGELOG.md
src/lib/st-alerts/alert-box/st-alert-box.component.html
src/lib/st-alerts/alert-box/st-alert-box.component.ts
src/lib/st-foreground-notifications/st-foreground-notifications.html
src/lib/st-foreground-notifications/st-foreground-notifications.ts
src/lib/st-info-box/st-info-box.component.html
src/lib/st-info-box/st-info-box.component.ts
src/lib/st-input/st-input.component.html
src/lib/st-input/st-input.component.ts
src/lib/st-modal/st-modal-buttons/st-modal-buttons.html
src/lib/st-modal/st-modal-buttons/st-modal-buttons.ts
src/lib/st-page-title/st-page-title.component.html
src/lib/st-page-title/st-page-title.component.ts
src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.html
src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.ts
src/lib/st-spinner/st-spinner.component.html
src/lib/st-spinner/st-spinner.component.spec.ts
src/lib/st-spinner/st-spinner.component.ts
src/lib/st-table/shared/st-table-row/st-table-row.component.scss
src/lib/st-tag-input/st-tag-input.component.html
src/lib/st-tag-input/st-tag-input.component.spec.ts
src/lib/st-tag-input/st-tag-input.component.ts
src/lib/st-textarea/st-textarea.component.html
src/lib/st-textarea/st-textarea.component.ts

refactor(egeo): Fix method calls from templates 

---

src/lib/st-label/st-label.component.ts
src/lib/st-tooltip/st-tooltip.component.ts

[NA]fix(st-tooltip): Tooltip content is initialized in OnInit

---

CHANGELOG.md
src/egeo-demo/st-table-demo/st-table-demo.component.html
src/lib/st-table/st-table.component.html
src/lib/st-table/st-table.component.scss
src/theme/components/_table.scss

[NA]fix(st-table): Fixed error with selectableAll and sortable columns

---

CHANGELOG.md
src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.html
src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.ts
src/lib/st-two-list-selection/list-item/list-item.component.html
src/lib/st-two-list-selection/list-item/list-item.component.scss
src/lib/st-two-list-selection/list-item/list-item.component.spec.ts
src/lib/st-two-list-selection/list-item/list-item.component.ts
src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
src/lib/st-two-list-selection/list-scroll/list-scroll.component.ts
src/lib/st-two-list-selection/list-selection/list-selection.component.html
src/lib/st-two-list-selection/list-selection/list-selection.component.ts
src/lib/st-two-list-selection/st-two-list-selection.component.ts
src/lib/st-two-list-selection/st-two-list-selection.model.ts
src/lib/st-two-list-selection/st-two-list-selection.module.ts
src/lib/st-two-list-selection/st-two-list-selection.view.component.html
src/lib/st-two-list-selection/st-two-list-selection.view.component.ts

feat(st-two-list): EGE-497 shows dropdown if  list is not editable.

---

src/egeo-demo/st-color-picker-demo/st-color-picker-demo.html
src/egeo-demo/st-color-picker-demo/st-color-picker-demo.module.ts
src/egeo-demo/st-color-picker-demo/st-color-picker-demo.ts
src/lib/st-color-picker/st-color-picker.component.spec.ts
src/lib/st-color-picker/st-color-picker.component.ts
src/lib/st-color-picker/st-color-picker.module.ts

[NA] feat(color picker): Implement interface ControlValueAccessor in order to can be used as part of a form

---

CHANGELOG.md
src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.component.scss
src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.html
src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
src/lib/st-dropdown-menu/README.md
src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.html
src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.spec.ts
src/lib/st-dropdown-menu/st-dropdown-menu.component.html
src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts

[EGE-499] feat(st-dropdown-menu): Allow to custom label and icon colors

---

CHANGELOG.md
src/lib/st-foreground-notifications/st-foreground-notifications.spec.ts
src/lib/st-foreground-notifications/st-foreground-notifications.ts

[NA]fix(st-foreground-notifications): Fix selected current notification

---

CHANGELOG.md
src/lib/st-header/menu-option/menu-option.html
src/lib/st-header/menu-option/menu-option.spec.ts
src/lib/st-header/menu-option/menu-option.ts

[NA]fix(st-header): Fixed st-header active option

---

tools/gulp/tasks/egeo-publish.ts

[NA]fix(egeo): Fix release task

---

tools/gulp/tasks/egeo-publish.ts

[NA]fix(egeo): Fix release destination folder

---

package.json
tools/gulp/package-tools/build-config.ts
tools/gulp/package-tools/build-release.ts
tools/gulp/package-tools/copy-files.ts
tools/gulp/package-tools/package-versions.ts
tools/gulp/tasks/egeo-publish.ts
tools/gulp/tasks/others.ts

[NA]fix(egeo): Fixed egeo version replace and licence copy

---

angular.json
projects/egeo-demo/src/package.json

[NA]fix(egeo): Added package.json to egeo-demo project

---

projects/egeo/package.json
tools/gulp/package-tools/build-release.ts

[NA]fix(egeo): Fixed egeo package.json copy

---

projects/egeo/package.json

[NA]fix(Egeo): Fixed egeo version

---

CHANGELOG.md
projects/egeo/src/lib/package.json

[NA] Fixed package.json main config

---

CHANGELOG.md
projects/egeo/package.json
projects/egeo/src/lib/package.json
tools/gulp/package-tools/build-release.ts

[NA] cherry-pick: fix package.json (construction task)

---

CHANGELOG.md
projects/egeo/package.json
projects/egeo/src/theme/components/_widget.scss

[NA] fix(theme): fix st-widget imports

---

CHANGELOG.md
projects/egeo/package.json
projects/egeo/src/theme/components/_widget.scss

[NA] cherry-pick: fix(theme) - fix st-widget imports

---

src/lib/package.json

[NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to in the internal package.json file

---

src/lib/package.json

[NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to in the internal package.json

---

CHANGELOG.md
src/lib/st-foreground-notifications/st-foreground-notifications.ts

[NA] fix(st-notifications): Fix refreshing notification statuses

---

CHANGELOG.md
angular.json
pom.xml
projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.component.scss
projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.html
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.spec.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
projects/egeo/src/theme/components/_dropdown-menu.scss

[EGE-505] feat(st-dropdown-menu): Allow to display a text info below label

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.html
projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.scss
projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.ts
projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.module.ts
projects/egeo/src/lib/st-bubble/st-bubble.component.html
projects/egeo/src/lib/st-bubble/st-bubble.component.spec.ts
projects/egeo/src/lib/st-bubble/st-bubble.component.ts
projects/egeo/src/theme/components/_bubble.scss

[EGE-506] feat(st-bubble): Allow to disable or enable animation and small theme and added functionality to open to left or right

---

CHANGELOG.md
package.json
src/lib/package.json

[NA] chore(package): Put version to 3.0.2 to fix compatibility error with internal library tweenjs

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.html
projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.module.ts
projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.scss
projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.ts
projects/egeo/src/lib/st-fullscreen-layout/README.md
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.html
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.spec.ts
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.ts
projects/egeo/src/theme/components/_fullscreen-layout.scss

[EGE-508] feat(st-fullscreen): Allow to display it on full width

---

projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss

[NA]fix(egeo-theme): Add batch icon class

---

projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.html
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.spec.ts
projects/egeo/src/theme/components/_fullscreen-layout.scss

[NA] feat(st-fullscreen):Add background color with full width

---

CHANGELOG.md

[NA] chore(changelog): update changelog

---

CHANGELOG.md
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.scss
projects/egeo/src/theme/components/_fullscreen-layout.scss

[NA]fix(fullscreen): changes in fixed padding

---

projects/egeo-demo/src/app/app.component.html
projects/egeo-demo/src/app/app.component.scss
projects/egeo-demo/src/app/modules/demos/demo-layout/demo.layout.scss
projects/egeo-demo/src/app/modules/home/home.scss
projects/egeo-demo/src/app/modules/theme/colors/colors.html
projects/egeo-demo/src/app/modules/theme/colors/colors.scss
projects/egeo-demo/src/app/modules/theme/fonts/fonts.html
projects/egeo-demo/src/app/modules/theme/fonts/fonts.scss
projects/egeo-demo/src/app/modules/theme/icons-demo/icons-demo.html
projects/egeo-demo/src/app/modules/theme/icons-demo/icons-demo.scss
projects/egeo-demo/src/app/shared/menu/menu.scss
projects/egeo-demo/src/styles.scss
projects/egeo/src/lib/st-menu/st-menu-options/st-menu-options.component.scss
projects/egeo/src/lib/utils/demo-generator/demo-generator.ts

[NA]feat(egeo-demo): Egeo demo layout improvements

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-alert-demo/st-alerts-demo.html
projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.html
projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.scss
projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.ts
projects/egeo-demo/src/app/demos/st-file-button-demo/st-file-button-demo.component.html
projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.html
projects/egeo-demo/src/app/demos/st-header-demo/st-header-demo.component.html
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-test-fullscreen-layout.component.ts
projects/egeo-demo/src/app/demos/st-switch-demo/st-switch-demo.html
projects/egeo-demo/src/app/demos/st-switch-demo/st-switch-demo.scss
projects/egeo-demo/src/app/demos/st-tag-input-demo/st-tag-input-demo.component.html
projects/egeo/src/lib/st-form-list/spec/st-form-list.component.spec.ts
projects/egeo/src/lib/st-form-list/st-form-list.html
projects/egeo/src/lib/st-form-list/st-form-list.scss
projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
projects/egeo/src/lib/st-form/st-form.component.html
projects/egeo/src/lib/st-fullscreen-layout/README.md
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.ts
projects/egeo/src/lib/st-modal/st-modal.service.spec.ts
projects/egeo/src/lib/st-modal/st-modal.service.ts
projects/egeo/src/theme/components/_button.scss

feat(egeo)[NA] Buttons styles refactor

---

projects/egeo/src/lib/st-table/st-table.component.html
projects/egeo/src/lib/st-table/st-table.component.spec.ts

[NA] fix(table): Fix event "selectedAll"

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-two-list-selection-demo/st-two-list-selection-demo.html
projects/egeo-demo/src/app/demos/st-two-list-selection-demo/st-two-list-selection-demo.ts
projects/egeo/src/lib/st-two-list-selection/list-item/list-item.component.spec.ts
projects/egeo/src/lib/st-two-list-selection/list-item/list-item.component.ts
projects/egeo/src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.model.ts
projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.spec.ts
projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.ts
projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.view.component.html
projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.view.component.spec.ts
projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.view.component.ts

[GS-1808] feat(st-two-list): allows to show and control movement of disabled items in origin list

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
projects/egeo/src/lib/st-modal/st-modal-buttons/st-modal-buttons.spec.ts
projects/egeo/src/lib/st-modal/st-modal-buttons/st-modal-buttons.ts
projects/egeo/src/lib/st-modal/st-modal.component.html
projects/egeo/src/lib/st-modal/st-modal.component.scss
projects/egeo/src/lib/st-modal/st-modal.component.ts
projects/egeo/src/lib/st-modal/st-modal.model.ts
projects/egeo/src/lib/st-modal/st-modal.service.spec.ts
projects/egeo/src/lib/st-modal/st-modal.service.ts
projects/egeo/src/theme/components/_modal.scss

[NA] feat(modals): apply new UX styles

---

CHANGELOG.md
projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.scss

 [NA] style(st-foreground-notifications): new ux style

---

projects/egeo/src/theme/components/_button.scss

[NA]fix(theme): Fix tool buttons height

---

CHANGELOG.md
projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.scss

[NA] style(st-foreground-notifications): new ux style

---

projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.html
projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.scss

[NA] Fix/styles foreground notifications

---

CHANGELOG.md
package.json
projects/egeo-demo/src/styles.scss

[NA]feat(demo): fix wrong path fonts

---

CHANGELOG.md
projects/egeo/src/lib/st-bubble/README.md
projects/egeo/src/lib/st-bubble/st-bubble.component.html
projects/egeo/src/lib/st-bubble/st-bubble.component.scss
projects/egeo/src/lib/st-bubble/st-bubble.component.spec.ts
projects/egeo/src/lib/st-bubble/st-bubble.component.ts
projects/egeo/src/theme/components/_bubble.scss

[NA] feat(st-bubble): Allow to add a max width from outside and cut words when there are longer than that width

---

CHANGELOG.md
projects/egeo/src/lib/index.ts
projects/egeo/src/lib/st-alerts/README.md
projects/egeo/src/lib/st-alerts/alert-box/README.md
projects/egeo/src/lib/st-alerts/alert-box/st-alert-box.component.spec.ts
projects/egeo/src/lib/st-alerts/alert-box/st-alert-box.component.ts
projects/egeo/src/lib/st-alerts/alert-box/st-alert-box.module.ts
projects/egeo/src/lib/st-alerts/st-alerts.component.ts
projects/egeo/src/lib/st-foreground-notifications/README.md
projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.ts

[NA] feat(st-alert): Publish alert box component to be used from outside and change link behaviour

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.html
projects/egeo/src/lib/index.ts
projects/egeo/src/lib/st-input/st-input.module.ts

[NA] fix(validator/clicloutside directives): Public directive modules in order to can be used from outside

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.html
projects/egeo/src/lib/index.ts
projects/egeo/src/lib/st-input/st-input.module.ts

Cherry pick [NA] fix(validator/clicloutside directives): Public directive modules in order to can be used from outside

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.html
projects/egeo/src/lib/index.ts
projects/egeo/src/lib/st-input/st-input.module.ts

Cherry pick: [NA] fix(validator/clickoutside directives): Public directive modules in order to can be used from outside

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
projects/egeo/src/lib/st-dropdown-menu/README.md
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.html
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.spec.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.module.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
projects/egeo/src/theme/components/_dropdown-menu.scss

[NA] feat(st-dropdown-menu): Allow to display a right aligned extra icon with bubble

---

projects/egeo/src/theme/components/_dropdown-menu.scss

[NA] fix(st-dropdown-menu): Fix wrong visualization of the right aligned icon

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-filter-selector-demo/st-filter-selector-demo.component.ts
projects/egeo/src/lib/st-dropdown-menu/README.md
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.html
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.html
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
projects/egeo/src/lib/st-filter-selector/README.md
projects/egeo/src/lib/st-filter-selector/st-filter-selector.component.spec.ts
projects/egeo/src/lib/st-filter-selector/st-filter-selector.component.ts
projects/egeo/src/lib/st-filter-selector/st-filter-selector.template.html

[NA] feat(st-dropdown-menu): Emit events when mouse enters and leaves an item

---

CHANGELOG.md
projects/egeo/src/lib/index.ts
projects/egeo/src/lib/pipes/pipes.module.ts
projects/egeo/src/lib/st-search/st-search.component.ts
projects/egeo/src/lib/utils/event-window-manager.ts

[NA]fix(Egeo): Fix Angular 9 compatibility issues

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/barrels.ts
projects/egeo-demo/src/app/demos/demos.routes.ts
projects/egeo-demo/src/app/demos/public_api.ts
projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.html
projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.module.ts
projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.scss
projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.ts
projects/egeo-demo/src/styles.scss
projects/egeo/src/lib/index.ts
projects/egeo/src/lib/st-vertical-icon-tabs/README.md
projects/egeo/src/lib/st-vertical-icon-tabs/st-icon-tabs.model.ts
projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.html
projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.scss
projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.spec.ts
projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.ts
projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.module.ts
projects/egeo/src/theme/components/_index.scss
projects/egeo/src/theme/components/_vertical-icon-tabs.scss
projects/egeo/src/theme/constants/_fonts.scss

[NA] feat(st-vertical-icon-tabs): Create component

---

projects/egeo-demo/src/app/demos/st-form-demo/form-editor/json-schema.ts
projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.component.scss
projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.html
projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.ts
projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.component.scss
projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.html
projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.module.ts
projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.ts
projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.scss
projects/egeo-demo/src/app/shared/title/title.component.scss
projects/egeo-demo/src/styles.scss
projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
projects/egeo/src/lib/st-form/st-form.component.html
projects/egeo/src/lib/st-form/st-form.component.ts
projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.scss
projects/egeo/src/theme/components/_form.scss

[NA] fix(st-form-demo): Improve dynamic form demo and fix some bugs

---

CHANGELOG.md
pom.xml

[NA] chore(release): Change version to 20.1.0

---

projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
projects/egeo/src/theme/components/_table.scss

[NA] fix(st-table): Fix style to header filter icon

---

projects/egeo-demo/src/app/demos/st-header-demo/st-header-demo.component.html
projects/egeo/src/lib/st-header/menu-option/menu-option.ts
projects/egeo/src/lib/st-header/st-header.component.spec.ts
projects/egeo/src/lib/st-header/st-header.component.ts
projects/egeo/src/theme/components/_header.scss

[NA] fix(st-header): Fix wrong visualization of user menu in small screen and change checking of option name sizes

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.scss
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
projects/egeo/src/lib/st-table/README.md
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
projects/egeo/src/lib/st-table/st-table.component.spec.ts
projects/egeo/src/theme/components/_table.scss

[NA] fix(st-table): Filtered header fields are introduced as input and they are not modified inside table component

---

package.json
projects/egeo/package.json

[NA]feat(egeo): Added egeo-ui-base as peerDependency

---

projects/egeo/src/theme/components/_modal.scss

[NA]fix(st-modal): Fix st-modal color variables

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.module.ts
projects/egeo-demo/src/app/shared/css-property-table/css-property-table.component.html
projects/egeo-demo/src/app/shared/css-property-table/css-property-table.component.scss
projects/egeo-demo/src/app/shared/css-property-table/css-property-table.component.ts
projects/egeo-demo/src/app/shared/css-property-table/css-property-table.model.ts
projects/egeo-demo/src/app/shared/css-property-table/css-property-table.module.ts
projects/egeo/src/theme/components/_breadcrumbs.scss
projects/egeo/src/theme/components/_button.scss
projects/egeo/src/theme/components/_dropdown-menu.scss
projects/egeo/src/theme/components/_form-base.scss
projects/egeo/src/theme/components/_fullscreen-layout.scss
projects/egeo/src/theme/components/_header.scss
projects/egeo/src/theme/components/_horizontal-tabs.scss
projects/egeo/src/theme/components/_search.scss
projects/egeo/src/theme/components/_sidebar.scss
projects/egeo/src/theme/components/_table.scss
projects/egeo/src/theme/components/_tag.scss
projects/egeo/src/theme/components/_vertical-icon-tabs.scss
projects/egeo/src/theme/components/_widget.scss
projects/egeo/src/theme/components/_zero-page.scss
projects/egeo/src/theme/utils/_fonts.scss

[NA] feat(table): Add css variables to customize some table colors and create main font css variable

---

projects/egeo/src/theme/components/_table.scss

[NA] fix(st-table): Fix error in header style

---

projects/egeo/src/lib/barrels.ts
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
projects/egeo/src/theme/components/_table.scss

[NA] fix(st-dynamic-table, st-vertical-icon-tabs): Add dynamic table and vertical icon tabs component to barrels file

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-tag-demo/st-tag-demo.component.html
projects/egeo/src/theme/components/_tag.scss

[NA] fix(st-tag): Fix default style without size class

---

projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.ts
projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.ts
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
projects/egeo/src/theme/components/_dynamic-table.scss
projects/egeo/src/theme/components/_index.scss
projects/egeo/src/theme/components/_sidebar.scss

[NA] fix(st-dynamic-table, st-sidebar): Fix some styles

---

CHANGELOG.md
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
projects/egeo/src/lib/st-table/shared/table-header.interface.ts
projects/egeo/src/lib/st-table/st-table.component.html
projects/egeo/src/lib/st-table/st-table.component.ts

[NA]feat(table): Add event when filter icon is clicked

---

CHANGELOG.md
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.scss
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
projects/egeo/src/lib/st-table/st-table.component.scss

- [X ] Add the issue in PR description

[NA]fix(table): Fix table filters popup position

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.scss
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.scss
projects/egeo/src/lib/st-dynamic-table/spec/st-dynamic-table.component.spec.ts
projects/egeo/src/lib/st-table/st-table.component.scss
projects/egeo/src/lib/st-table/st-table.component.spec.ts
projects/egeo/src/lib/st-table/st-table.component.ts
projects/egeo/src/theme/components/_dynamic-table.scss
projects/egeo/src/theme/components/_table.scss

[FC-24]feat(st-table): Add sticky header to st-table

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.html
projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.ts
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.scss
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts

[NA]feat(dynamicTable): Add Fk's and groups to dynamic table

---

projects/egeo/src/lib/index.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts

[NA]fix(dynamicTable): fix set of fields and export fk types

---

projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.ts

[NA] fix(st-dynamic-table): Fix emitted fk value and form field interface

---

CHANGELOG.md
projects/egeo/src/theme/components/_button.scss
projects/egeo/src/theme/constants/_colors.scss

[NA]feat(egeo-theme): Update button colors

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.html
projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.ts
projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.html
projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.module.ts
projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.ts
projects/egeo-demo/src/app/demos/st-form-demo/visual-customization/st-theme-customization-demo.component.scss
projects/egeo-demo/src/app/demos/st-form-demo/visual-customization/st-theme-customization-demo.html
projects/egeo-demo/src/app/demos/st-form-demo/visual-customization/st-theme-customization-demo.ts
projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.ts
projects/egeo/src/lib/st-form/README.md
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.ts
projects/egeo/src/lib/st-form/st-form.component.html
projects/egeo/src/lib/st-form/st-form.component.scss
projects/egeo/src/lib/st-form/st-form.component.ts
projects/egeo/src/lib/st-pagination/st-pagination.component.ts
projects/egeo/src/theme/components/_form.scss
projects/egeo/src/theme/components/_sidebar.scss
projects/egeo/src/theme/constants/_colors.scss
projects/egeo/src/theme/utils/_forms.scss

[NA] feat(st-form): Allow to customize some styles using css variables and fix bug in pagination component

---

CHANGELOG.md
projects/egeo/src/lib/st-fullscreen-layout/README.md
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.html
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.scss
projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.ts
projects/egeo/src/theme/components/_fullscreen-layout.scss

[NA]feat(st-fullscreen-layout): Add close button to fullscreen

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.html
projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.ts
projects/egeo-demo/src/app/demos/st-form-demo/visual-customization/st-theme-customization-demo.ts
projects/egeo/src/lib/index.ts
projects/egeo/src/lib/st-form/README.md
projects/egeo/src/lib/st-form/spec/resources/json-schema.ts
projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.html
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.ts
projects/egeo/src/lib/st-form/st-form.component.html
projects/egeo/src/lib/st-form/st-form.component.ts
projects/egeo/src/lib/st-form/st-form.model.ts
projects/egeo/src/theme/components/_form.scss
projects/egeo/src/theme/components/_table.scss

[NA] feat(st-form): Define interfaces and allow to display a link before field using property 'link' in ui block

---

CHANGELOG.md
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts

[NA]feat(dynamicTable): Add types to fields

---

projects/egeo/src/theme/components/_modal.scss

[NA] fix(st-modal): Fix title weight

---

projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts

[NA] fix(st-dynamic-table): Update header fields when json schema or ui definitions are updated

---

projects/egeo/package.json

[NA]fix(egeo): Moved json-schema dependency from devDependeny to dependency in final json

---

CHANGELOG.md
projects/egeo/src/lib/st-select/st-select.html
projects/egeo/src/lib/st-select/st-select.ts

[NA] fix(st-select): Fix bug when select is used without being part of a form and selected is changed from outside

---

projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.scss
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.html
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.scss
projects/egeo-demo/src/app/demos/st-tag-input-demo/st-tag-input-demo.component.scss

[NA]fix(st-select): Added st-select without form demo

---

CHANGELOG.md
projects/egeo/src/lib/st-select/st-select.html
projects/egeo/src/lib/st-select/st-select.ts

Cherry pick: [NA] fix(st-select): Fix bug when select is used without being part of a form and selected is changed from outside 

---

projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.scss
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.html
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.scss
projects/egeo-demo/src/app/demos/st-tag-input-demo/st-tag-input-demo.component.scss

[NA]fix(st-select): St-select no form demo

---

CHANGELOG.md
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.spec.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts

[NA] feat(st-dynamic-table): Allow to hide a field through the UI definitions

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
projects/egeo/src/lib/st-table/st-table.component.html
projects/egeo/src/lib/st-table/st-table.component.spec.ts
projects/egeo/src/lib/st-table/st-table.component.ts
projects/egeo/src/lib/st-table/st-table.module.ts
projects/egeo/src/theme/components/_table.scss

[NA] feat(st-table): Close filter menu when user clicks outside

---

projects/egeo/src/theme/components/_table.scss

[NA] fix(st-table): Revert header changes when table does not have sticky hover menu

---

CHANGELOG.md
projects/egeo/src/lib/st-pagination/st-pagination.component.spec.ts
projects/egeo/src/lib/st-pagination/st-pagination.component.ts

[NA] fix(st-pagination): Remove duplicated event emitted when items per page are changed

---

CHANGELOG.md
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts

[NA]feat(dynamicTable): manage default ordering in table component

---

CHANGELOG.md
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.spec.ts
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
projects/egeo/src/theme/components/_table.scss

[NA] feat(st-table):st-table: Filter menus are displayed aligned to the left side of their cell

---

projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.scss
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.spec.ts
projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
projects/egeo/src/theme/components/_table.scss

[NA] fix(st-table): Simplify filter menu position calculation and added needed css variable

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.html
projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.scss
projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.ts
projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.module.ts
projects/egeo/src/lib/st-checkbox/st-checkbox.component.html
projects/egeo/src/theme/components/_checkbox.scss

[NA] feat(st-checkbox): Allow to customize the checked icon styles from outside using css variables

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-zero-page-demo/st-zero-page-demo.component.html
projects/egeo-demo/src/app/demos/st-zero-page-demo/st-zero-page-demo.component.ts
projects/egeo-demo/src/app/demos/st-zero-page-demo/st-zero-page-demo.module.ts
projects/egeo/src/theme/components/_zero-page.scss

[NA] feat(st-zero-page): Allow to customize some styles from outside using css variables

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-form-demo/visual-field-improvements/st-visual-field-improvements-editor-demo.html
projects/egeo/src/lib/st-dynamic-table/README.md
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
projects/egeo/src/lib/st-form/README.md
projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.ts
projects/egeo/src/lib/st-form/st-form-field/st-form-field.interface.ts
projects/egeo/src/lib/st-form/st-form.component.html
projects/egeo/src/lib/st-form/st-form.component.ts
projects/egeo/src/lib/st-form/st-form.model.ts

[NA] feat(st-form): Allow to customize option labels using UI Definition object and render selects with integer value

---

projects/egeo/src/theme/components/_form.scss

[NA]feat(egeo-theme): Add cursor text in readonly mode

---

CHANGELOG.md
projects/egeo/src/lib/st-dynamic-table/README.md
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts

[NA] fix(st-dynamic-table): Fix bug in foreign key management when property does not exist on row

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.ts
projects/egeo/src/theme/components/_bubble.scss

[NA] feat(st-bubble): Allow to customize paddings and fix wrong css variables

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.html
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.module.ts
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.scss
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
projects/egeo/src/lib/st-select/st-select.html
projects/egeo/src/lib/st-select/st-select.scss
projects/egeo/src/theme/components/_select.scss

[NA] fix(st-dropdown): Fix functionality to change the focused option with arrow keys and added css variables to customize styles

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.component.scss
projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
projects/egeo/src/lib/st-form/st-form.component.ts
projects/egeo/src/lib/st-form/st-form.model.ts

[SN-63] feat(st-form): Allow to hide a field without depending on another one

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.html
projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.ts
projects/egeo/src/lib/st-sidebar/README.md
projects/egeo/src/lib/st-sidebar/st-sidebar.component.html
projects/egeo/src/lib/st-sidebar/st-sidebar.component.spec.ts
projects/egeo/src/lib/st-sidebar/st-sidebar.component.ts
projects/egeo/src/theme/components/_sidebar.scss

[NA] feat(st-sidebar): Display an optional message when search does not have any results and removed change event emitted after searching something

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.html
projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.module.ts
projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
projects/egeo/src/theme/components/_dropdown-menu.scss

[NA] feat(st-dropdown-menu): Allow to customize some styles from outside using css variables

---

projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
projects/egeo/src/theme/components/_dropdown-menu.scss

[NA] feat(st-dropdown-menu): Add css variable to border color when active

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-search-demo/st-search-demo.html
projects/egeo-demo/src/app/demos/st-search-demo/st-search-demo.module.ts
projects/egeo-demo/src/app/demos/st-search-demo/st-search-demo.ts
projects/egeo/src/lib/st-search/st-search.component.html
projects/egeo/src/lib/st-search/st-search.component.scss
projects/egeo/src/lib/st-search/st-search.component.spec.ts
projects/egeo/src/theme/components/_search.scss

[NA] feat(st-search): Allow to customize icon styles from outside using css variables

---

projects/egeo-demo/src/app/demos/st-search-demo/st-search-demo.ts
projects/egeo/src/theme/components/_search.scss

[NA] fix(st-search): Fix wrong css variables

---

CHANGELOG.md
projects/egeo-demo/src/app/app.module.ts
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
projects/egeo-demo/src/app/demos/st-modal2-demo/st-modal2-demo.component.html
projects/egeo-demo/src/app/demos/st-modal2-demo/st-modal2-demo.component.ts
projects/egeo/src/lib/st-modal/st-modal.component.html
projects/egeo/src/lib/st-modal/st-modal.component.spec.ts
projects/egeo/src/lib/st-modal/st-modal.component.ts
projects/egeo/src/lib/st-modal/st-modal.service.spec.ts
projects/egeo/src/lib/st-modal/st-modal.service.ts
projects/egeo/src/lib/st-modal2/st-modal2.component.html
projects/egeo/src/lib/st-modal2/st-modal2.component.spec.ts
projects/egeo/src/lib/st-modal2/st-modal2.component.ts

[NA] feat(st-modal): adds fadein fadeout animation

---

projects/egeo/src/lib/st-modal/st-modal.component.ts
projects/egeo/src/lib/st-modal/st-modal.service.ts

[NA] fix(st-modal): fix disabled animation in modal

---

projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
projects/egeo-demo/src/app/demos/st-modal2-demo/st-modal2-demo.component.html
projects/egeo/src/lib/st-modal/st-modal.component.ts
projects/egeo/src/lib/st-modal/st-modal.service.ts
projects/egeo/src/lib/st-modal2/st-modal2.component.ts

[NA] feat(modals): disable animation by default

---

projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
projects/egeo/src/theme/components/_dropdown-menu.scss

[NA] fix(st-dropdown-menu): Revert active border to deprecated color

---

projects/egeo/src/lib/st-dynamic-table/spec/st-dynamic-table.component.spec.ts
projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts

[NA] feat(st-dynamic-table): Catch error when it tries to format an invalid date

---

CHANGELOG.md
projects/egeo/src/lib/barrels.ts
projects/egeo/src/lib/index.ts
projects/egeo/src/lib/st-item-list/item-list-item/item-list-item.component.html
projects/egeo/src/lib/st-item-list/item-list-item/item-list-item.component.scss
projects/egeo/src/lib/st-item-list/item-list-item/item-list-item.component.spec.ts
projects/egeo/src/lib/st-item-list/item-list-item/item-list-item.component.ts
projects/egeo/src/lib/st-item-list/item-list-scroll/item-list-scroll.component.html
projects/egeo/src/lib/st-item-list/item-list-scroll/item-list-scroll.component.scss
projects/egeo/src/lib/st-item-list/item-list-scroll/item-list-scroll.component.spec.ts
projects/egeo/src/lib/st-item-list/item-list-scroll/item-list-scroll.component.ts
projects/egeo/src/lib/st-item-list/st-item-list.component.html
projects/egeo/src/lib/st-item-list/st-item-list.component.scss
projects/egeo/src/lib/st-item-list/st-item-list.component.spec.ts
projects/egeo/src/lib/st-item-list/st-item-list.component.ts
projects/egeo/src/lib/st-item-list/st-item-list.model.ts
projects/egeo/src/lib/st-item-list/st-item-list.module.ts

[NA]revert(st-item-list-item): Revert remove st-item-list-item

---

CHANGELOG.md
projects/egeo/src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.spec.ts
projects/egeo/src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.ts

[FC-99] fix(st-sidebar): Reset expanded list when items are changed

---

CHANGELOG.md
pom.xml
projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.html
projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.scss
projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.ts
projects/egeo/src/theme/components/_button.scss

[FC-97] feat(st-button): Apply new design according to UX specifications

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.html
projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.scss
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.scss
projects/egeo/src/theme/components/_modal.scss

[FC-27] fix(st-modal): Fix wrong visualization of large titles

---

CHANGELOG.md
projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.html
projects/egeo-demo/src/app/demos/st-select-demo/select-demo.ts
projects/egeo-demo/src/app/demos/st-tag-input-demo/st-tag-input-demo.component.html
projects/egeo-demo/src/app/demos/st-tag-input-demo/st-tag-input-demo.component.ts
projects/egeo-demo/src/styles.scss
projects/egeo/src/lib/st-select/st-select.html
projects/egeo/src/lib/st-select/st-select.spec.ts
projects/egeo/src/lib/st-tag-input/st-tag-input.component.html
projects/egeo/src/lib/st-tag-input/st-tag-input.component.scss
projects/egeo/src/lib/st-tag-input/st-tag-input.component.spec.ts
projects/egeo/src/theme/components/_dropdown-menu.scss
projects/egeo/src/theme/components/_form-base.scss
projects/egeo/src/theme/components/_input.scss
projects/egeo/src/theme/components/_search.scss
projects/egeo/src/theme/components/_select.scss
projects/egeo/src/theme/components/_tag-input.scss
projects/egeo/src/theme/utils/_forms.scss

[FC-106] feat(st-input, st-select, st-tag-input): Apply new design according to UX specifications
