Stratio/egeo

src/lib/st-switch/st-switch.component.ts, src/lib/st-switch/st-switch.html
- Bugfix
Switch does not change when user clicks on it twice
=> fix(st-switch): Switch does not change when user clicks on it twice

CHANGELOG.md, src/lib/st-table/shared/table-header.interface.ts, src/lib/st-table/st-table.component.html, src/lib/st-table/st-table.component.scss, src/lib/st-table/st-table.component.spec.ts, src/lib/st-table/st-table.component.ts
BREAKING CHANGE: Sortable inputs is deprecated
- Improvement
Allow Able or disable order for columns singly
test powered by @EvaMGC 
=> feat(st-table): Allow to enable or disable order for columns singly

CHANGELOG.md, src/lib/st-switch/st-switch.component.spec.ts, src/lib/st-switch/st-switch.component.ts, src/lib/st-switch/st-switch.html
- Bugfix
Close #EGE-271
Switch component emits event twice when user interacts with it
=> fix(st-switch): Switch component emits event twice

CHANGELOG.md, src/demo-app/app/app.routing.ts, src/demo-app/app/layout/layout.menu.ts, src/lib/barrels.ts, src/lib/public_api.ts, src/lib/st-select/demo/select-demo.html, src/lib/st-select/demo/select-demo.module.ts, src/lib/st-select/demo/select-demo.ts, src/lib/st-select/st-select.component.html, src/lib/st-select/st-select.component.scss, src/lib/st-select/st-select.component.spec.ts, src/lib/st-select/st-select.component.ts, src/lib/st-select/st-select.module.ts
- Refactor
BREAKING CHANGE: Rename StCombobox to StSelect
Closes EGE-393
=> refactor(StCombobox): Rename StCombobox to StSelect

CHANGELOG.md, src/egeo-demo/st-search-demo/st-search-demo.ts, src/lib/st-search/st-search.component.spec.ts, src/lib/st-search/st-search.component.ts
=> fix(st-search): Send event with an empty search when user presses the cross button

CHANGELOG.md, src/lib/st-search/demo/st-search-demo.ts, src/lib/st-search/st-search.component.spec.ts, src/lib/st-search/st-search.component.ts
=> fix(st-search): Cherry pick "Send event with an empty search when user presses the cross button"

CHANGELOG.md, src/egeo-demo/st-select-demo/select-demo.ts, src/lib/st-select/st-select.component.html, src/lib/st-select/st-select.component.spec.ts, src/lib/st-select/st-select.component.ts
=> refactor(st-select):  Output emitted when select is changed is now the value of the option instead of the entire option

CHANGELOG.md, src/lib/st-alerts/alert-box/st-alert-box.component.spec.ts, src/lib/st-breadcrumbs/st-breadcrumbs.component.html, src/lib/st-select/st-check-validations.ts, src/theme/components/_breadcrumbs.scss
=> fix(st-breadcrumbs)[CCT-502]: Remove left padding from the first item and right padding from the last one

CHANGELOG.md, src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.html, src/lib/st-tag-input/README.md, src/lib/st-tag-input/st-tag-input.component.spec.ts, src/lib/st-tag-input/st-tag-input.component.ts
=> feat(st-tag-input)[UX-7]: Add functionality to not allow user to type forbidden values

CHANGELOG.md, src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.html, src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.ts, src/lib/st-tag-input/README.md, src/lib/st-tag-input/st-tag-input.component.html, src/lib/st-tag-input/st-tag-input.component.spec.ts, src/lib/st-tag-input/st-tag-input.component.ts
=> feat(st-tag-input)[UX-17]: Add functionality to not allow user to type values with invalid format

CHANGELOG.md, src/egeo-demo/st-input-demo/st-input-demo.html, src/egeo-demo/st-input-demo/st-input-demo.ts, src/theme/utils/_forms.scss
=> fix(st-input)[UX-29]: Add a gray color to input text when it is disabled and it has value

CHANGELOG.md, src/lib/st-pagination/st-pagination.component.spec.ts, src/lib/st-pagination/st-pagination.component.ts
=> fix(st-pagination)[UX-35]: Fix error when a change is listened from outside and remove actions when it is being created

CHANGELOG.md, src/egeo-demo/st-form-demo/json-schema.ts, src/lib/st-form/spec/st-form.component.spec.ts, src/lib/st-form/st-form.component.html, src/lib/st-form/st-form.component.ts
=> CHERY-PICK: fix(st-form): Remove dependant fields when parent does not have any value

CHANGELOG.md, src/lib/st-pop/st-pop.component.spec.ts, src/lib/st-pop/st-pop.component.ts, src/lib/st-select/st-select.scss
=> fix(st-select)[UX-89]: When select is opened after scrolling, its dropdown is not displayed

src/egeo-demo/st-select-demo/select-demo.html, src/lib/st-form/st-form-field/st-form-field.component.html, src/lib/st-form/st-form-field/st-form-field.component.spec.ts, src/lib/st-form/st-form-field/st-form-field.component.ts, src/lib/st-select/st-select.spec.ts, src/lib/st-select/st-select.ts, src/theme/components/_input.scss
=> fix(st-select)[UX-93]: Allow to reset value after user selects an empty option

CHANGELOG.md, src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.html, src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.ts, src/lib/st-foreground-notifications/st-foreground-notifications.ts
=> [NA]fix(st-foreground-notifications): Two way binding for visible input

CHANGELOG.md, src/lib/st-input/st-input.component.html, src/lib/st-input/st-input.component.spec.ts
=> [NA] feat(st-input): Label is only generated if it is not empty

.classpath, CHANGELOG.md, package.json, src/demo-app/tsconfig-build.json, src/lib/package.json, src/lib/st-item-list/item-list-scroll/item-list-scroll.component.html, src/lib/st-item-list/item-list-scroll/item-list-scroll.component.scss, src/lib/st-item-list/item-list-scroll/item-list-scroll.component.spec.ts, src/lib/st-item-list/st-item-list.component.spec.ts, src/lib/st-item-list/st-item-list.module.ts, src/lib/st-two-list-selection/list-scroll/list-scroll.component.html, src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss, src/lib/st-two-list-selection/list-scroll/list-scroll.component.spec.ts, src/lib/st-two-list-selection/list-selection/list-selection.component.spec.ts, src/lib/st-two-list-selection/st-two-list-selection.component.spec.ts, src/lib/st-two-list-selection/st-two-list-selection.module.ts, src/lib/st-two-list-selection/st-two-list-selection.view.component.spec.ts, tools/package-tools/rollup-helpers.ts
Replace deprecated dependency for ngx-virtual-croller.
=> [EGE-433]feat(Global): Replace deprecated dependency with ngx-virtual-scroller

CHANGELOG.md, src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.html, src/lib/st-breadcrumbs/README.md, src/lib/st-breadcrumbs/st-breadcrumbs-item/st-breadcrumbs-item.component.html, src/lib/st-breadcrumbs/st-breadcrumbs.component.html, src/lib/st-breadcrumbs/st-breadcrumbs.component.spec.ts, src/lib/st-breadcrumbs/st-breadcrumbs.component.ts, src/lib/st-breadcrumbs/st-breadcrumbs.interface.ts, src/theme/components/_breadcrumbs.scss
=> [EGE-442] fix(st-breadcrumbs): Allow to configure visualization mode as "default" or "title"

src/lib/public_api.ts
=> [NA] fix(breadcrumbs): Publish StBreadCrumbMode to can be referenced from outside

CHANGELOG.md, src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.html, src/lib/st-breadcrumbs/st-breadcrumbs.component.scss
=> [NA] fix(st-breadcrumb): breadcrumb with a long text displays displaced section

CHANGELOG.md, src/lib/st-two-list-selection/list-selection/list-selection.component.html, src/lib/st-two-list-selection/list-selection/list-selection.component.spec.ts, src/lib/st-two-list-selection/list-selection/list-selection.component.ts, src/lib/st-two-list-selection/st-two-list-selection.spec.ts
=> Cherry-pick [EGE-477] fix(two-list): Searcher disappears when user is  typing and introduces a text without results

CHANGELOG.md, angular.json, src/lib/public_api.ts, src/lib/st-search/st-search.component.spec.ts, src/lib/st-search/st-search.component.ts, src/lib/st-search/st-search.model.ts
Now, It is possible to know who emits the search event.  There are four options:
**INPUT** --> Interacting with the textbox
**LIST** --> Clicking on an option from the autocomplete list
**FILTER** --> Changing the current filter
**ENTER**  --> Pressing the enter key
=> [EGE-480] feat(st-search): Allow to differentiate search events by its origin

CHANGELOG.md, package.json
=> [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to fix compatibility error with internal library tweenjs

CHANGELOG.md, package.json
=> Cherry pick [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to fix compatibility error with internal library tweenjs

projects/egeo/src/lib/st-bubble/st-bubble.component.scss
=> [NA] fix(st-bubble): Center text when it is shorter than bubble's width

CHANGELOG.md, projects/egeo/src/lib/st-search/st-search.component.html, projects/egeo/src/lib/st-search/st-search.component.ts
before there was only one event to search, but there was no exclusive event for when we changed the filter option.
=> [NA]feat(st-search): Add new Output event when select a filter
